Merge with new unassigned user code.
usdoj-crt/crt-portal pull request #1029
Opened 2021-11-04 14:24 UTC by billyhunt

[Link to ZenHub issue.](link-goes-here)

## What does this change?

This PR syncs up the current dashboard code with  the changes made for unassigned users.  

## Screenshots (for front-end PR):

## Checklist:

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2021-11-04 14:55 UTC, louh approved these changes

2021-11-04 22:57 UTC, louh requested changes
This feels a little faster locally, can't wait to see the improvement on dev.

2021-11-04 22:57 UTC, louh commented on crt_portal/cts_forms/filters.py
> +    print("selected_actor => ", selected_actor)
Noticed an extra debug print here

2021-11-04 22:57 UTC, louh commented on crt_portal/cts_forms/templates/forms/complaint_view/dashboard/index.html
>  <script type="text/javascript" src="{% static 'vendor/aria-autocomplete-1.2.3.min.js' %}"></script>
We may as well remove the script tag here too.

2021-11-05 19:34 UTC, louh approved these changes

2021-11-08 14:36 UTC, ilodidoj approved these changes

2021-11-08 14:36 UTC, merged