Initial commit
usdoj-crt/crt-portal pull request #1034
Opened 2021-11-10 15:30 UTC by billyhunt

[Link to ZenHub issue.](https://github.com/usdoj-crt/crt-portal-management/issues/1133)

## What does this change?

Names and Addresses currently display "None" in empty fields on printed form letter.  This change will remove the word "None" and leave it blank for any field.  

**note** when testing, make sure to try different combinations of address fields to make sure the fields with data still populate.

## Screenshots (for front-end PR):

# Previous
![image](https://user-images.githubusercontent.com/6232068/141141415-17a137aa-05b1-435a-9a37-e8197d2f8c7d.png)
![image](https://user-images.githubusercontent.com/6232068/141142145-b6618044-6b7f-49ea-bc6e-44ca1cf3ac04.png)

# After update
![image](https://user-images.githubusercontent.com/6232068/141141817-715ad3bf-22e2-4ff7-823e-838ace3c304a.png)
![image](https://user-images.githubusercontent.com/6232068/141141998-53db5fd6-c7cd-4ed0-aeb2-486e99001fc6.png)

## Checklist:

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2021-11-10 17:54 UTC, billyhunt commented
Updated to show email address.

![image](https://user-images.githubusercontent.com/6232068/141166652-5641bc83-4843-4c49-aeac-4211e1bf120f.png)

2021-11-10 18:34 UTC, louh requested changes
I haven't usually commented on git hygiene on this project but I think it's most warranted here, can we rewrite the history so that "Initial commit" doesn't get merged in?

Alternatively, we can resolve this by squash-merging or rebase-merging this branch, but that means one of us would need to remember to select that option during the merge.

2021-11-10 18:34 UTC, louh commented on crt_portal/cts_forms/templates/forms/complaint_view/print/form_letter.html
> +      {% if data.contact_email %}
Should `data.contact_email` also be added to the list of conditionals in line 19?

2021-11-10 19:19 UTC, billyhunt commented
>I haven't usually commented on git hygiene on this project but I think it's most warranted here, can we rewrite the history >so that "Initial commit" doesn't get merged in?

I am OK with that in theory, but have never done it. What does that process entail?

2021-11-12 17:44 UTC, louh approved these changes

2021-11-12 18:13 UTC, merged