Bh/form letters 10 21
usdoj-crt/crt-portal pull request #1035
Opened 2021-11-10 15:46 UTC by billyhunt

[Link to ZenHub issue.](https://github.com/usdoj-crt/crt-portal-management/issues/1129)
[Link to ZenHub issue.](https://github.com/usdoj-crt/crt-portal-management/issues/1130)
[Link to ZenHub issue.](https://github.com/usdoj-crt/crt-portal-management/issues/1131)
[Link to ZenHub issue.](https://github.com/usdoj-crt/crt-portal-management/issues/1132)

## What does this change?

We are adding 4 DRS form letters to refer users to the correct agency.  I added all of these in the same PR to minimize the chance  of problems in the database migration.   

## Screenshots (for front-end PR):

![image](https://user-images.githubusercontent.com/6232068/141144761-5bd13f15-2ae2-4e71-b782-e838aa78d567.png)
![image](https://user-images.githubusercontent.com/6232068/141145164-88c1ac82-16a1-4d03-b8ee-b823ef433db8.png)
![image](https://user-images.githubusercontent.com/6232068/141144848-53d752af-16c1-4724-b20f-d4b249df0ee1.png)
![image](https://user-images.githubusercontent.com/6232068/141144905-e3eb2e59-9e52-4c7b-a58a-ea1c2c1df71a.png)
![image](https://user-images.githubusercontent.com/6232068/141144938-74efee26-d04f-4096-b1ed-59eb9f9552e3.png)

## Checklist:

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2021-11-10 19:19 UTC, louh requested changes
@billyhunt Can you also squash/edit/rebase your commit history to remove the churn on the address template?

2021-11-10 19:19 UTC, louh commented on crt_portal/cts_forms/migrations/0126_drs_hhs_referral_letter.py
> +    templates = ResponseTemplate.objects.filter(title__icontains='DRS - EEOC Referral Form Letter')
I think the filter string here needs to match this template name

2021-11-10 19:19 UTC, louh commented on crt_portal/cts_forms/migrations/0127_drs_dot_referral_letter.py
> +    templates = ResponseTemplate.objects.filter(title__icontains='DRS - EEOC Referral Form Letter')
Same comment re: filter string

2021-11-10 19:19 UTC, louh commented on crt_portal/cts_forms/migrations/0128_drs_dept_of_ed_referral_letter.py
> +    templates = ResponseTemplate.objects.filter(title__icontains='DRS - EEOC Referral Form Letter')
Same comment re: filter string

2021-11-10 19:33 UTC, billyhunt commented
> @billyhunt Can you also squash/edit/rebase your commit history to remove the churn on the address template?

Lets chat about it.  I don't usually like to modify or squash commit histories, but am open to changing.

2021-11-12 20:20 UTC, louh approved these changes

2021-11-12 20:35 UTC, merged