Add new hate crimes button, logic to show it, and translations.
usdoj-crt/crt-portal pull request #1100
Opened 2022-02-08 19:10 UTC by billyhunt

[Link to ZenHub issue.](https://github.com/usdoj-crt/crt-portal-management/issues/1181)

## What does this change?

The hate crimes section of the landing page should link to our internal "hate-crime-human-trafficking.html" page, with translations added for the button in all languages.  

## Screenshots (for front-end PR):

<img width="622" alt="Screen Shot 2022-02-08 at 2 03 01 PM" src="https://user-images.githubusercontent.com/6232068/153057476-270d34cc-a48e-426b-ae04-54c5ee82b1a2.png">

## Checklist:

+ [ ] Refresh your cache.  Then go to the home page, click "Workplace discrimination or other employment-related problem".  From the dropdown select "Victim of a hate crime"
+ [ ] is the "Get help for hate crimes" button there?  
+ [ ] Click the button and make sure you are taken to the "hate-crime-human-trafficking" page.

**Check the following languages**

+ [ ] Spanish
Consiga ayuda en relación con un delito de odio
+ [ ] Traditional Chinese
為尋求仇恨犯罪的幫助
+ [ ] Simplified Chinese
为寻求仇恨犯罪的帮助
+ [ ] Vietnamese
Nhận sự giúp đỡ khi gặp phải những hành vi phạm tội do thù hận
+ [ ] Tagalog
Humingi ng tulong para sa mga krimen ng pagka-poot
+ [ ] Korean
증오 범죄에 대한 도움 요청

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2022-02-08 20:18 UTC, louh commented
The font styling on the two buttons are different. I can see that the button is true to the design mockup, but should they also be consistent in some way?
<img width="595" alt="Screen Shot 2022-02-08 at 3 15 23 PM" src="https://user-images.githubusercontent.com/2553268/153068376-ec30d9b0-c830-46d9-b5d2-09337011f6b7.png">
<img width="605" alt="Screen Shot 2022-02-08 at 3 15 31 PM" src="https://user-images.githubusercontent.com/2553268/153068378-7dd61495-848c-4bba-a2fd-d06f1628980a.png">

2022-02-08 20:23 UTC, louh requested changes

2022-02-08 20:23 UTC, louh commented on crt_portal/cts_forms/templates/landing.html
> +                  <a class="usa-button usa-button--outline" aria-label="{% trans 'Get help for hate crimes' %}" href="./hate-crime-human-trafficking">{% trans "Get help for hate crimes" %}</a>
I don't think we need to have an  [`aria-label`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) here that duplicates the link text content.

2022-02-10 16:12 UTC, billyhunt commented
Updates.  What do you all think @louh and @chinelo-ikejimba?

<img width="626" alt="Screen Shot 2022-02-10 at 11 00 57 AM" src="https://user-images.githubusercontent.com/6232068/153448575-951b9017-002a-4d07-9135-b4969e3fe496.png">
<img width="619" alt="Screen Shot 2022-02-10 at 11 00 50 AM" src="https://user-images.githubusercontent.com/6232068/153448576-2b2faaad-2103-4aec-8f4c-b38d1b75a403.png">

2022-02-10 18:58 UTC, chinelo-ikejimba commented
> Updates. What do you all think @louh and @chinelo-ikejimba?
> 
> <img alt="Screen Shot 2022-02-10 at 11 00 57 AM" width="626" src="https://user-images.githubusercontent.com/6232068/153448575-951b9017-002a-4d07-9135-b4969e3fe496.png">
> 
> <img alt="Screen Shot 2022-02-10 at 11 00 50 AM" width="619" src="https://user-images.githubusercontent.com/6232068/153448576-2b2faaad-2103-4aec-8f4c-b38d1b75a403.png">

@billyhunt great progress! Please un-italicize the hyperlinks and they'll be good to go.

2022-02-10 20:12 UTC, louh approved these changes

2022-02-10 20:56 UTC, merged