[WIP DO NOT MERGE] /webpack prototype
usdoj-crt/crt-portal pull request #1169
Opened 2022-05-12 17:19 UTC by billyhunt

[Link to ZenHub issue.](link-goes-here)

## What does this change?

## Screenshots (for front-end PR):

## Checklist:

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2022-05-17 21:04 UTC, eileen-nava commented
I have a comment about the `localhost:8000/housing-resources` bullet point below:
>  - [ ] Test all external links. Make sure a modal appears if the site is directing you to a non Justice Department Site.

I see a modal when I click some links, but not all.  

Links where I saw modals:
-  Equifax, Experian, and Trans Union.  
- [Homelessness Resources](https://www.hudexchange.info/housing-and-homeless-assistance/)
- [American Bar Association](https://www.americanbar.org/groups/legal_services/flh-home/)
- [Legal Services Corporation (or Legal Aid Offices)](https://www.lsc.gov/find-legal-aid)


Links where I did NOT see modals:
- [Consumer Financial Protection Bureau](https://www.consumerfinance.gov/complaint/).
-  [Fair Housing Accessibility First](https://www.hud.gov/program_offices/fair_housing_equal_opp/accessibility_first_home) 
-  [U.S. Department of Housing and Urban Development](https://www.hud.gov/program_offices/fair_housing_equal_opp/online-complaint).
- [Office of Public & Indian Housing](https://www.hud.gov/program_offices/public_indian_housing/)
- [Office of Inspector General (OIG)](https://www.hudoig.gov/about/where-were-located)
- [Fair Housing Initiatives Program Agencies](https://www.hud.gov/program_offices/fair_housing_equal_opp/partners/FHIP)
- [Fair Housing Assistance Program Agencies](https://www.hud.gov/program_offices/fair_housing_equal_opp/partners/FHAP/agencies)
- [Rent and Utility Payment Assistance](https://www.consumerfinance.gov/coronavirus/mortgage-and-housing-assistance/renter-protections/find-help-with-rent-and-utilities/)
- [State Attorneys General](https://www.usa.gov/state-attorney-general)
- [USA.Gov](https://www.usa.gov/)

2022-05-17 22:17 UTC, billyhunt commented
I believe the rule set is if it is a government agency we do not need to show a modal. If it is we do. @ilodidoj can you confirm?

2022-05-18 12:49 UTC, ilodidoj commented
@billyhunt @eileen-nava usually for 508 compliance if the URL is pointing to different site the the source origin, modal will be needed.  In our case all federal agencies are part of greater FEDERAL umbrella, therefore no modal. Modal will be needed for non-federal entities as it is now.

2022-05-18 12:51 UTC, ilodidoj commented
@billyhunt please check any branch conflict and resolve them before assigning for PR review. CC: @eileen-nava @JackRyan1989

2022-05-18 13:02 UTC, eileen-nava commented
> @billyhunt @eileen-nava usually for 508 compliance if the URL is pointing to different site the the source origin, modal will be needed. In our case all federal agencies are part of greater FEDERAL umbrella, therefore no modal. Modal will be needed for non-federal entities as it is now.

I didn't know about this distinction! TIL!  Thanks for sharing.

2022-05-18 15:51 UTC, ilodidoj commented
@billyhunt please check the CI/CD error and resolve the issue. crt-django version should be updated as well in package.json; just a thought.  CC: @eileen-nava @JackRyan1989

2022-05-18 16:45 UTC, billyhunt commented
Interesting idea on the versioning.  We have not really been doing releases so far.  Do you think we should start @ilodidoj? What should it be?  2.0?  1.1?

2022-05-19 15:46 UTC, JackRyan1989 commented on Dockerfile
> +RUN npm install webpack -g
Just noting here that my system seems to hang on this step. We may need to note in the install documentation that if the installation seems to hang up here, users should do an npm install before docker-compose up.

2022-05-19 15:50 UTC, JackRyan1989 commented on crt_portal/cts_forms/templates/forms/pro_template.html
>  {% load static %}
I think load static is unnecessary?

2022-05-19 15:53 UTC, JackRyan1989 commented on crt_portal/cts_forms/templates/forms/question_cards/commercial_public_location.html
> +{% render_bundle 'commercialPublicLocation' %}
Does this work without importing the render_bundle from webpack_loader?

2022-05-19 15:53 UTC, JackRyan1989 commented on crt_portal/cts_forms/templates/forms/report_base.html
>  {% load static %}
Can we remove?

2022-05-19 15:56 UTC, JackRyan1989 commented on crt_portal/cts_forms/templates/landing.html
>    </script>
Maybe in a future PR we extract this inline JS to a new component?

2022-05-19 16:07 UTC, JackRyan1989 commented on package.json
> +    "webpack-merge": "^5.8.0"
Do we use webpack merge?

2022-05-19 16:10 UTC, JackRyan1989 requested changes
I think the templates can be cleaned up a bit. There are some .html files that only import static files for the JS, and since that is no longer being done by the Django build process, we can remove that import and avoid any confusion there. There's one file that uses a built module without importing webpack_bundler into the template, and I'm not sure if that will cause an issue?

2022-05-19 20:52 UTC, JackRyan1989 approved these changes

2022-05-19 20:53 UTC, merged