Improve copy experience for Campaign URLs
usdoj-crt/crt-portal pull request #1303
Opened 2023-01-18 20:11 UTC by okkays

## What does this change?

- 🌎 The admin page includes a list of campaigns
- ⛔ The common use-case is to copy the campaign URL, but the URL is:
  * Static text, so you have to click to copy
  * Prepended with the incorrect host when not on production
- ✅ This commit adds a (re-usable) copy script that makes links easier to copy, and deals with relative vs absolute urls.

## Screenshots (for front-end PR):

![copy](https://user-images.githubusercontent.com/15126660/213283819-6ff3e896-c9b7-4741-933d-ebf5af28f786.gif)

## Checklist:

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2023-01-19 15:30 UTC, JackRyan1989 requested changes
I'm hesitant to request the changes because they are very minor. But I think you should consider adding a label to the input to enhance the accessibility of the page.

2023-01-19 15:30 UTC, JackRyan1989 commented on crt_portal/cts_forms/admin.py
> +        return mark_safe(f'<input disabled="disabled" class="admin-copy absolute-url" value="{url}"/>')
When running Waves on the admin page to check for a11y issues, it flagged 1 error, and that was that this <input> element did not have an associated label. I'm not sure if disabling the input affects the need for a label, but I would slap one on there for good measure.

2023-01-19 21:31 UTC, okkays commented on crt_portal/static/sass/admin.scss
> +  margin: 0 10px !important;
Good callout - also changed it to grow the input box 👍

2023-01-20 17:01 UTC, JackRyan1989 approved these changes
Looks great!

2023-01-23 19:33 UTC, ilodidoj approved these changes
@okkays this can be merged to dev.

2023-01-23 19:52 UTC, merged