Fix links in response template
usdoj-crt/crt-portal pull request #1358
Opened 2023-03-23 19:46 UTC by kewitham

[Issue #1493](https://github.com/usdoj-crt/crt-portal-management/issues/1493)

## What does this change?
This PR fixes the links in the HCE form letter and updates the turndown logic to allow for underscore (_) characters in llinks

## Screenshots (for front-end PR):

## Checklist:

+ [ ] Verify that the links in the HCE Form response template are not broken - /admin/cts_forms/responsetemplate/126/change/
+ [ ] Verify that you are able to add a link with an underscore and it renders properly

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2023-03-24 00:48 UTC, okkays approved these changes
Thanks for the fix!

2023-03-24 19:31 UTC, okkays requested changes

2023-03-27 20:20 UTC, kewitham commented on crt_portal/static/vendor/turndown.js
> -        replacement = node.isCode ? node.nodeValue : self.escape(node.nodeValue);
@okkays updated to remove this change and created a task to fix the bug - https://github.com/usdoj-crt/crt-portal-management/issues/1509

2023-03-28 19:06 UTC, okkays approved these changes

2023-03-28 19:06 UTC, merged