Make grouping query more efficient, fix bulk actions bug
usdoj-crt/crt-portal pull request #1384
Opened 2023-04-11 20:33 UTC by kewitham

[Issue #1527](https://github.com/usdoj-crt/crt-portal-management/issues/1527)
[Issue #1524](https://github.com/usdoj-crt/crt-portal-management/issues/1524)
[Issue #1528](https://github.com/usdoj-crt/crt-portal-management/issues/1528)

## What does this change?
This updates the grouping query to make it more efficient in the following ways:
1. Removing the count() query for each group
2. Applying the filters before grouping to reduce the number of reports to group
3. Removing an extra unnecessary grouping query

It also fixes the bulk actions in groups so they only apply to members of the group.

## Screenshots (for front-end PR):

## Checklist:

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2023-04-12 20:45 UTC, okkays requested changes
A few quick changes to make, but mostly lgtm

Can you explain in words how this makes things more efficient, and what kinds of improvements you're seeing on dev? (how do you know that this will work)

2023-04-12 20:45 UTC, okkays commented on crt_portal/cts_forms/views.py
> +            query_string = return_url_args
```suggestion
        query_string = request.POST.get('query_string', return_url_args)
```

2023-04-12 20:45 UTC, okkays commented on crt_portal/cts_forms/views.py
> +    final_data = group_view_data[len(group_view_data) - 1]["data"]
```suggestion
    final_data = group_view_data[-1]["data"]
```

2023-04-13 13:42 UTC, okkays approved these changes
LGTM!

2023-04-13 14:00 UTC, ilodidoj approved these changes
@kewitham ready for dev merge.

2023-04-13 19:12 UTC, merged