Kw/ga fixes
usdoj-crt/crt-portal pull request #1426
Opened 2023-06-08 14:56 UTC by kewitham

[Link to ZenHub issue.](link-goes-here)

## What does this change?

This PR updates the GA code to not use exports because they were creating errors.

## Screenshots (for front-end PR):

## Checklist:

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2023-06-12 14:52 UTC, okkays requested changes
I realize you're moving this code around, but a couple of tweaks to the existing code.

2023-06-12 14:52 UTC, okkays commented on crt_portal/static/js/ga_util.js
> +    }
I don't think you actually need the index, here:

```suggestion
    navItems.forEach(navItem => {
      navItem.addEventListener('click', e =>
        sendGAPublicClickEvent('main nav ' + e.target.innerText)
      );
    });
```

2023-06-13 18:50 UTC, okkays approved these changes

2023-06-14 16:24 UTC, ilodidoj approved these changes
LGTM!

2023-06-20 14:08 UTC, merged