Add new api route for referral flow
usdoj-crt/crt-portal pull request #1447
Opened 2023-06-27 19:25 UTC by kewitham

[Link to ZenHub issue.](link-goes-here)

## What does this change?

## Screenshots (for front-end PR):

## Checklist:

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2023-07-03 14:43 UTC, okkays requested changes

2023-07-03 14:43 UTC, okkays commented on crt_portal/api/views.py
> +                response = f'Referral email template #{template.id} failed to send to report #{report.id}: {e}'
this try-except is a bit broad (nothing is ever going to go wrong with the `if email_response else` portion unless there's a syntax error in the code, in which case you _don't_ want to catch the exception.

These kinds of nested blocks can be simplified a bit if you're able to return early. For example, maybe instead:

```py
if action == 'send':
  response = {'preview': preview}
  try:
    email_response = crt_send_mail(report, template)
  except Exception as e:
    return Response({'email_response': f'Referral email template #{template.id} failed to send to report #{report.id}: {e}', **response})
  if not email_response:
    return Response({'email_response': f'Referral email template #{template.id} failed to send to report #{report.id}', **response})
  return Response({'email_response': f'Sent referral email template #{template.id} to report #{report.id}', **response})
```

You could further reduce nesting (especially if 'copy' and 'print' turn out to be complicated) by making a helper function for the `if action == 'send'` portion

2023-07-05 16:42 UTC, ilodidoj commented on crt_portal/api/views.py
> +                    response = f'Referral email template #{template.id} failed to send to report #{report.id}'
@kewitham @okkays we do get reasons for failure some times, it's the error field under TMS Emails > Error message field. But I think this happen later once we pass the msg to TMS client.

2023-07-05 18:56 UTC, kewitham commented on crt_portal/api/views.py
> +                    response = f'Referral email template #{template.id} failed to send to report #{report.id}'
crt_send_mail function calls the [send_mail function](https://docs.djangoproject.com/en/4.2/topics/email/) which only returns 0 or 1 depending on how many messages are successful so I'm not sure how we would include the additional information.

2023-07-05 20:00 UTC, okkays commented on crt_portal/api/views.py
> +                    response = f'Referral email template #{template.id} failed to send to report #{report.id}'
Sounds good. Then I'd just return a `502` if something goes wrong (indicating the mail service failed to send)

2023-07-06 20:21 UTC, okkays requested changes

2023-07-06 20:21 UTC, okkays commented on crt_portal/api/views.py
> +            return Response({'response': '500: No action provided', **preview})
I don't think this actually returns a 500

also - 500 should be in the event of a unexpected server error (our code broke) this should probably be 400

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_client_errors

https://docs.djangoproject.com/en/4.2/ref/request-response/#jsonresponse-objects

```suggestion
            return JsonResponse(
              {
                'message': 'No action provided',
                **preview,
              }, status=400
              )
```

2023-07-07 14:16 UTC, okkays requested changes
sorry for the extra back and forth, lgtm after this

2023-07-07 14:16 UTC, okkays commented on crt_portal/api/views.py
> +                return Response({'response': f'502: Referral email template #{template.id} failed to send to report #{report.id}: {e}', **preview})
Sorry, here as well

2023-07-07 14:16 UTC, okkays commented on crt_portal/api/views.py
> +                return Response({'response': f'502: Referral email template #{template.id} failed to send to report #{report.id}', **preview})
- And here

2023-07-07 18:40 UTC, okkays approved these changes

2023-07-07 18:40 UTC, okkays commented
(Approved pending test updates to match the new statuses!)

2023-07-10 12:32 UTC, ilodidoj commented
@kewitham @okkays Probably need to fix the unit test issue before merging, CI/CD failure needs to be resolved.

2023-07-11 13:59 UTC, merged