Kk/1647/email card pdf links
usdoj-crt/crt-portal pull request #1568
Opened 2023-10-20 17:37 UTC by okkays

[Link to issue](https://github.com/usdoj-crt/crt-portal-management/issues/1647)

## What does this change?

Exposes the TMS PDF views (bulk and single) on the report detail page.

## Screenshots (for front-end PR):

[tms_for_report_id_1208.pdf](https://github.com/usdoj-crt/crt-portal-management/files/13056969/tms_for_report_id_1208.pdf)

[tms_id_503.pdf](https://github.com/usdoj-crt/crt-portal-management/files/13056970/tms_id_503.pdf)

<img width="414" alt="image" src="https://github.com/usdoj-crt/crt-portal-management/assets/15126660/42ed5105-1720-465e-87ac-0bc762fabbec">

## Checklist:

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2023-10-24 14:04 UTC, kewitham requested changes
A couple UI things but lgtm!

2023-10-25 18:08 UTC, okkays commented on crt_portal/cts_forms/templates/forms/complaint_view/show/email_responses_card.html
> +      </small>
Done - added some custom language and hid the entire table (although in practice, the autoresponse should always mean there's a response)

2023-10-25 18:09 UTC, okkays commented on crt_portal/cts_forms/templates/forms/complaint_view/show/email_responses_card.html
>  <table class="usa-table usa-table--borderless card-table width-full">
These column headers are pretty cramped, but renamed it to "ID" 😅

The export will still name it as "TMS ID".

2023-10-26 15:02 UTC, kewitham approved these changes

2023-10-26 15:07 UTC, merged