Disposition page site tour POC
usdoj-crt/crt-portal pull request #1604
Opened 2023-11-27 17:35 UTC by kewitham

[Spike: find site tour package](https://github.com/usdoj-crt/crt-portal-management/issues/1657)
[Disposition Page - In-app onboarding flow#1667](https://github.com/usdoj-crt/crt-portal-management/issues/1667)

## What does this change?

This PR adds a site tour package called [shepherd js](https://shepherdjs.dev/) to guide users through the new disposition page.

## Screenshots (for front-end PR):
![Image](https://github.com/usdoj-crt/crt-portal-management/assets/18104884/9f8d66b0-7a46-4163-9407-34d6c1930ce5)

## Checklist:

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2023-11-29 17:44 UTC, okkays requested changes
![shepherd-tour](https://github.com/usdoj-crt/crt-portal/assets/15126660/44023ab5-eae1-4cce-a107-4eee2005187a)

Because of the redirect when I go to the disposition page, the site tour appears momentarily and then is skipped on refresh.

---

Also, some weird stuff is happening when I scroll down during the tour - it looks like maybe it's trying to highlight the tabs?

<img width="582" alt="image" src="https://github.com/usdoj-crt/crt-portal/assets/15126660/1585c8ae-0fcc-4a52-82b9-982e8d2ccf61">

2023-11-29 17:44 UTC, okkays commented on crt_portal/static/js/tour.js
> +      'The <b>other scheduled reports</b> tab shows reports that have expiration dates more than 30 days in the future.',
(prefer `strong` to `b` for [accessibility reasons](https://stackoverflow.com/a/271776/13231999))

2023-11-29 17:44 UTC, okkays commented on crt_portal/static/js/tour.js
> +  if (!localStorage.getItem('shepherd-tour')) {
nit: setting shepherd-tour to `'no'` will still suppress the tour (which is probably fine)

2023-11-29 17:44 UTC, okkays commented on crt_portal/static/vendor/shepherd.js
sidenote, possible for a future tech task: is it necessary to include this in `vendor` even if we have it in package.json? `gulp` ought to be able to copy the vendor javascript to the correct directory following `npm install`

2023-11-30 16:32 UTC, kewitham commented on crt_portal/static/vendor/shepherd.js
created an [issue](https://github.com/usdoj-crt/crt-portal-management/issues/1679) in the backlog for this

2023-11-30 16:33 UTC, okkays approved these changes
LGTM - ready to demo!

2023-12-01 18:59 UTC, merged