Kw/1698/saved search page
usdoj-crt/crt-portal pull request #1696
Opened 2024-02-05 17:53 UTC by kewitham

[Link to ZenHub issue.](link-goes-here)

## What does this change?

## Screenshots (for front-end PR):

## Checklist:

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2024-02-12 21:53 UTC, okkays requested changes

2024-02-12 21:53 UTC, okkays commented on crt_portal/cts_forms/migrations/0194_profile_saved_searches_savedsearch_section.py
> +            name='saved_searches',
<img width="884" alt="image" src="https://github.com/usdoj-crt/crt-portal/assets/15126660/86182ad4-755a-4254-8ce6-075394d7b9d9">

2024-02-13 16:21 UTC, okkays approved these changes
Really good sized PR - it's super clear what's going on

2024-02-14 18:45 UTC, ilodidoj reviewed
@kewitham crt_portal/cts_forms/urls.py showing conflict bottom of this PR. Is this resolved or should be resolved before merge? CC; @okkays

2024-02-14 18:47 UTC, okkays commented
> @kewitham crt_portal/cts_forms/urls.py showing conflict bottom of this PR. Is this resolved or should be resolved before merge? CC; @okkays

(This is because of the PR I just merged - it will force Katie to resolve it before it can be merged)

2024-02-15 21:47 UTC, merged