Add inmate number to the pro form contact info
usdoj-crt/crt-portal pull request #1867
Opened 2024-07-11 22:44 UTC by okkays

https://github.com/usdoj-crt/crt-portal-management/issues/1898

## What does this change?

- 🌎 Incarcerated persons receive mail only with inmate number
- ⛔ We don't record inmate number
- ✅ This commit adds a field for it to the internal side of the app

## Screenshots (for front-end PR):

PR up!

Can be edited on `/form/view/<id>`:

![Image](https://github.com/user-attachments/assets/7e4f0575-7e4d-4eff-91f9-f1fc72adbcb9)

Can be viewed on `/form/view/<id>`:

![Image](https://github.com/user-attachments/assets/87883c5a-b7f9-460d-a8c6-df597777f77b)

Does not affect the normal form:

![Image](https://github.com/user-attachments/assets/b97ad682-ab87-45e9-b258-1d8f20ebb08f)

Affects the pro form:

![Image](https://github.com/user-attachments/assets/231826dd-cf53-4dfa-9441-45e1a81563be)

## Checklist:

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2024-07-15 18:41 UTC, kewitham requested changes
Should we pull this into the referral and contact letters too?

2024-07-15 20:12 UTC, okkays commented
> Should we pull this into the referral and contact letters too?

Good idea - I've [added a followup ticket](https://github.com/usdoj-crt/crt-portal-management/issues/1911) for the next sprint to capture this

2024-07-15 20:27 UTC, kewitham approved these changes

2024-07-16 17:43 UTC, kewitham commented
@okkays just spoke to @ilodidoj and he flagged that we need to consider Anthony's export if we are adding a field. We should add it as the last field of the export so it doesn't interfere with the existing order

2024-07-18 15:19 UTC, merged