Bugfix: updating assigned_to shows id of original user
usdoj-crt/crt-portal pull request #678
Opened 2020-09-21 18:53 UTC by cantsin

No Zenhub issue

## What does this change?

Fixes a bug where updating the assignee shows the id of the original user, which is not helpful. See screenshot below (bottom is older behavior, top is newer behavior).

## Screenshots (for front-end PR):

![2020-09-21_11-51](https://user-images.githubusercontent.com/3013175/93808493-ea572280-fc00-11ea-90ad-dd19dc72e35b.png)

## Checklist:

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.)
+ [x] Check for [accessibility](/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.)
+ [ ] Re-check for [accessibility](/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2020-09-21 19:01 UTC, Jkrzy requested changes
Nice catch, thanks @cantsin. It would be great to get some test coverage for `get_actions` here. I'm going to make a new card for that, we'll implement on this branch, and then merge.

2020-11-06 15:55 UTC, Jkrzy commented
@cantsin, can you take a look at the changes @ilodidoj and @timoballard paired on above?

2020-11-09 17:18 UTC, cantsin commented
Thanks y'all! Appreciate the tests, they look good.

That being said ... this PR has a bug ... and it's entirely my fault. To reproduce, create a new report and attempt to assign someone. You will get a `User matching query does not exist` error because the id is blank (passed in to `User.objects.get`). 

Can we fix this bug, and add one more test for this bugfix pretty please? :grimacing: :pray:

2020-11-12 15:20 UTC, Jkrzy commented
@timoballard, @ilodidoj ya'll want to pair on this one again and tackle @cantsin's [comment](https://github.com/usdoj-crt/crt-portal/pull/678#issuecomment-724153128)?

2020-11-17 19:18 UTC, ilodidoj commented
fixed bug and new test added.

2020-11-17 19:42 UTC, timoballard reviewed
Good stuff @ilodidoj - left one comment on where you can expand the test coverage a bit.

2020-11-17 19:42 UTC, timoballard commented on crt_portal/cts_forms/tests/test_forms.py
> +            pass
@ilodidoj - we should be able to test some output here. Much like `test_user_assignment` above, there should be a single "Assigned to" action coming back from `get_actions`. To get a feel for how to write the test, I'd suggest simply printing the action to the console here, but in the end it should look pretty similar to lines 54-55 above. 

Let me know if you want to pair on this, would be happy to!

2020-11-17 20:58 UTC, timoballard approved these changes

2020-11-17 20:59 UTC, merged