New housing bullet with Spanish translation
usdoj-crt/crt-portal pull request #682
Opened 2020-09-23 15:05 UTC by hakhalid11

[Link to ZenHub issue.](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/704)

## What does this change?
This adds a new bullet for the housing primary complaint examples. It also adds Spanish translation for the requested bullet

## Screenshots (for front-end PR):
![image](https://user-images.githubusercontent.com/66343959/94031138-8b261900-fd8c-11ea-93b9-f0921cacc09b.png)

![image](https://user-images.githubusercontent.com/66343959/94031201-9da05280-fd8c-11ea-8e5f-8c94952eb3aa.png)

## Checklist:

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.)
+ [x] Check for [accessibility](/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.)
+ [ ] Re-check for [accessibility](/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2020-09-23 23:19 UTC, cantsin approved these changes
Looks good! One question, did you re-run `makemessages`? Usually we like to update the rest of this translation file (including `POT-Creation-Date` so it's easy to tell at a glance when the file was updated). The file lines also change occasionally. Wondering if these changes were omitted for a reason? 

Otherwise, LGTM

2020-09-24 16:34 UTC, Jkrzy requested changes
+1 to @cantsin's review, we need to make these changes with `makemessages`

2020-09-24 17:14 UTC, hakhalid11 commented
@cantsin Ahh that makes sense. I was initially hesitant to commit so many changes in one file but your explanation makes sense thank you.

2020-09-24 17:15 UTC, hakhalid11 commented
@Jkrzy I ran makemessages updating django.po file. 👍

2020-09-24 17:27 UTC, cantsin commented on crt_portal/cts_forms/locale/es/LC_MESSAGES/django.po
> +msgstr ""
This one is on me. But I think it's OK since we aren't doing spanish translations for the back end.

2020-09-24 17:27 UTC, cantsin approved these changes
LGTM

2020-09-24 17:27 UTC, merged