updated 404 page error text
usdoj-crt/crt-portal pull request #703
Opened 2020-10-13 14:16 UTC by hakhalid11

[Link to ZenHub issue.](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/705)

## What does this change?
Based on feedback from product owner this change updates the 404 page error text. Feedback can be found on the ZenHub card, in the comments section.
## Screenshots (for front-end PR):
![image](https://user-images.githubusercontent.com/66343959/95872559-ed938900-0d3c-11eb-93c6-a27159560fe8.png)
## Checklist:

### Author
hakhalid11

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.)
+ [x] Check for [accessibility](/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.)
+ [ ] Re-check for [accessibility](/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2020-10-13 15:26 UTC, Jkrzy requested changes
Doesn't meet acceptance criteria updated in https://github.com/18F/crt-portal/issues/705#issuecomment-707297365

`Try returning to the previous page` is still rendering on the 404 page.

We should also take this opportunity to make these telephone numbers clickable so they're consistent with all the others on the site.

2020-10-13 16:02 UTC, hakhalid11 commented
I pushed the urls.py instead of views.py with the msg change. I also updated the phones to links thanks for the suggestion.

2020-10-13 19:43 UTC, Jkrzy requested changes

2020-10-13 19:43 UTC, Jkrzy commented on crt_portal/cts_forms/templates/forms/errors.html
> +              <li><a href="tel:1-855-856-1247">1-855-514-0716</a> {% trans '(toll-free)' %}</li>
The links and text don't match here, which one is correct?

2020-10-14 15:59 UTC, Jkrzy requested changes
Thanks for correcting the phone numbers! There's a typo in the  street for mailing address we need to remedy as well. `Pennsylvannia`.

2020-10-16 12:59 UTC, Jkrzy approved these changes

2020-10-16 12:59 UTC, merged