[WIP] correctional_facility_type prison type filter added
usdoj-crt/crt-portal pull request #925
Opened 2021-07-28 18:20 UTC by ilodidoj

[Link to issue.](https://github.com/usdoj-crt/crt-portal-management/issues/986)

## What does this change?
Allow filter view all table by prison type

## Screenshots (for front-end PR):

## Checklist:

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2021-07-29 22:56 UTC, billyhunt approved these changes
Looks good to me!

2021-07-29 22:56 UTC, billyhunt commented on crt_portal/cts_forms/forms.py
> +            'correctional_facility_type',
Do we prefer commas on the last item of an array or not?

2021-07-30 13:45 UTC, billyhunt requested changes
Actually, I am not sure it is working.  When I create a new item with a private prison, and search for it, I see all records, and the selection is not saved on reload.

2021-07-30 14:56 UTC, ilodidoj commented
> Actually, I am not sure it is working. When I create a new item with a private prison, and search for it, I see all records, and the selection is not saved on reload.

Hi @billyhunt I am thinking there might be an issue of JS script not updated on your local.  Please close docker, remove all images except the database image from docker images.  Remove the local stack volume only. Rebuild with docker-compose up --build when this PR is checked out.  This should resolve any local stack issue and JS update.  Let me know if you still see the same behavior after doing these steps. Thanks.

2021-07-30 20:46 UTC, billyhunt approved these changes
You were correct Imran.  Wiping everything and starting with new docker containers was my problem.  

All tests pass.  Flake8 tests pass.  The code looks good to me!

2021-08-02 17:40 UTC, merged