Hotfix for Tagalog SPL form
usdoj-crt/crt-portal pull request #966
Opened 2021-09-03 14:40 UTC by billyhunt

[Link to ZenHub issue.](https://github.com/usdoj-crt/crt-portal-management/issues/1018)

## What does this change?

Hotfix for tagalog update.

## Screenshots (for front-end PR):

## Checklist:

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

2021-09-03 17:36 UTC, louh requested changes

2021-09-03 17:36 UTC, louh commented on crt_portal/cts_forms/migrations/0122_update_spl_tagalog.py
> +from django.db import migrations
This is a repeated line?

2021-09-03 17:52 UTC, louh approved these changes

2021-09-07 14:38 UTC, billyhunt commented
Closing to wait on official updated translation.

2021-09-07 14:38 UTC, closed without merging